[2023-07-11 20:28:57] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:28:57] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:29:02] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:29:07] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:29:12] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:29:17] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:29:20] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:29:25] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:29:30] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:29:35] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:29:40] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:29:45] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:29:50] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:29:50] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:29:55] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:30:00] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:30:05] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:30:10] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:30:15] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:30:20] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:30:20] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:30:25] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:30:30] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:30:35] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:30:40] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:30:45] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:30:50] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:30:50] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:30:55] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:31:00] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:31:05] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:31:10] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:31:15] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:31:20] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:31:20] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:31:25] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:31:30] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:31:35] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:31:40] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:31:45] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:31:50] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:31:50] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:31:55] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:32:00] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:32:05] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:32:10] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:32:15] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:32:20] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 20:32:20] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 21:21:09] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 21:37:36] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 21:54:10] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 22:10:48] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 22:28:47] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 22:44:55] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 23:01:37] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 23:17:45] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 23:34:22] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
[2023-07-11 23:49:28] | ERROR | [utils_kafka.py:26:delivery_callback] - message failed delivery: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
NoneType: None
